### ISSUE TITLE
Project Checklist

### ISSUE THREAD

**Issue by phillycc** [ResponymousApp/Responymous#1]
- [x] Github Organization
  - [x] Invited everyone?
  - [x] Everyone accepted?
  - [x] Everyone forked?
- [x] User Stories
  - [x] Written?
  - [x] Reviewed?
  - [x] Estimated?
  - [x] Revised?
- [x] Mockups
  - [x] Written?
  - [x] Reviewed?
  - [x] Revised?
- [ ] Project Architecture
  - [ ] Written?
  - [ ] Reviewed?
  - [ ] Revised?
- [x] Issues and Milestones
  - [x] Written?
  - [x] Reviewed?
  - [x] Revised?
- [ ] Build and Deployment
  - [x] Created `gh-pages` branch?
  - [x] Pushed _something_?
  - [x] Initial release?
  - [x] Mid-term release?
  - [ ] Final release?
  - [x] Bugfixes?
