### ISSUE TITLE
Authentication to-do's

### ISSUE THREAD

**Issue by phillycc** [ResponymousApp/Responymous#6]
The following data must be written to Firebase upon authentication:
- [x] users
  - [x] access_token (pulled from GitHub)
  - [x] email (pulled from GitHub)
  - [x] name (pulled from GitHub)
  - [x] student (default to true)
- [x] classUsers
  - [x] class_id (pulled from querystring param)
  - [x] user_id (pulled from GitHub)
  - [x] current_vote (default to 5)
  - [x] joinedOn (date)
  - [x] student (default to true)

These are all the fields that are "touched" when the user first gets authenticated.
